"""Export a recipe to standalone, readable pandas — no CleanFrame dependency.

``result.code.save("clean_customers.py")`` produces a plain ``clean(df)`` function
you can read, diff, and drop into a pipeline that never imports CleanFrame. The
transforms are reproduced faithfully (with small self-contained helpers for the
non-trivial ones like number/date parsing); validation rules are emitted as
comments, since quarantine is a CleanFrame runtime concept rather than a pandas
one-liner.
"""

from __future__ import annotations

from collections.abc import Callable

from .ops import DEFAULT_NA_TOKENS
from .recipe import Recipe
from .types import Op

_HEADER = '''"""Auto-generated by CleanFrame. Deterministic, dependency-free pandas.

Edit freely — this file has no third-party dependency. Regenerate with
``result.code.save(...)`` if you change the recipe.
"""

import re

import numpy as np
import pandas as pd

_NA_TOKENS = {tokens}
_CURRENCY_SYMBOLS = {"₹": "INR", "$": "USD", "€": "EUR", "£": "GBP", "¥": "JPY"}
_CODE_RE = re.compile(r"\\b([A-Z]{3})\\b")


def _smap(series, fn):
    """Apply fn to string cells only; leave NaN and non-strings untouched."""
    return series.map(lambda v: fn(v) if isinstance(v, str) else v)


def _to_na(series, tokens=None):
    toks = _NA_TOKENS if tokens is None else {str(t).strip().casefold() for t in tokens}
    return _smap(series, lambda v: np.nan if v.strip().casefold() in toks else v)


def _parse_number(series, decimal=".", thousands=",", symbols=()):
    def one(v):
        if v is None or (isinstance(v, float) and np.isnan(v)) or isinstance(v, bool):
            return np.nan if not isinstance(v, (int, float)) or isinstance(v, bool) else float(v)
        if isinstance(v, (int, float)):
            return float(v)
        s = str(v).strip()
        if not s:
            return np.nan
        neg = s.startswith("(") and s.endswith(")")
        if neg:
            s = s[1:-1]
        for sym in symbols:
            s = s.replace(sym, "")
        keep = set("0123456789+-") | {decimal, thousands}
        s = "".join(ch for ch in s if ch in keep)
        if "-" in s:
            neg = True
        s = s.replace(thousands, "").replace("+", "").replace("-", "")
        if decimal != ".":
            s = s.replace(decimal, ".")
        if s in ("", "."):
            return np.nan
        try:
            val = float(s)
        except ValueError:
            return np.nan
        return -val if neg else val

    return series.map(one)


def _parse_date(series, formats=None, dayfirst=False, output="%Y-%m-%d"):
    if formats:
        result = pd.Series(pd.NaT, index=series.index, dtype="datetime64[ns]")
        for fmt in formats:
            mask = result.isna() & series.notna()
            if not mask.any():
                break
            result.loc[mask] = pd.to_datetime(series[mask], format=fmt, errors="coerce")
        dt = result
    else:
        dt = pd.to_datetime(series, errors="coerce", dayfirst=dayfirst)
    if str(output).lower() in ("datetime", "raw", "none"):
        return dt
    return dt.dt.strftime(output).where(dt.notna(), np.nan)


def _detect_currency(v, default=None):
    if not isinstance(v, str):
        return default
    for sym, code in _CURRENCY_SYMBOLS.items():
        if sym in v:
            return code
    m = _CODE_RE.search(v.upper())
    return m.group(1) if m else default


def _normalize_phone(series, default_country_code=None):
    def one(v):
        if v is None or (isinstance(v, float) and np.isnan(v)):
            return v
        s = str(v)
        plus = s.strip().startswith("+")
        digits = re.sub(r"\\D", "", s)
        if not digits:
            return np.nan
        if plus:
            return "+" + digits
        if default_country_code:
            cc = re.sub(r"\\D", "", str(default_country_code))
            if cc and digits.startswith(cc):
                return "+" + digits
            return "+" + cc + digits.lstrip("0")
        return digits

    return series.map(one)


_UNIT_FACTORS = {
    "kg": 1000.0, "g": 1.0, "mg": 0.001, "lb": 453.59237, "oz": 28.349523125,
    "km": 1000.0, "m": 1.0, "cm": 0.01, "mm": 0.001, "in": 0.0254, "ft": 0.3048,
    "l": 1.0, "ml": 0.001, "gal": 3.785411784,
}
_UNIT_FAMILY = {
    "kg": "mass", "g": "mass", "mg": "mass", "lb": "mass", "oz": "mass",
    "km": "length", "m": "length", "cm": "length", "mm": "length", "in": "length", "ft": "length",
    "l": "volume", "ml": "volume", "gal": "volume",
}
_UNIT_RE = re.compile(r"^\\s*([+-]?\\d+(?:[.,]\\d+)?)\\s*([A-Za-z]+)\\s*$")


def _normalize_unit(series, to="g"):
    to = str(to).casefold()
    target_fam = _UNIT_FAMILY[to]
    target_factor = _UNIT_FACTORS[to]

    def one(v):
        if v is None or (isinstance(v, float) and np.isnan(v)):
            return np.nan
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            return float(v)
        m = _UNIT_RE.match(str(v))
        if not m:
            return np.nan
        amount = float(m.group(1).replace(",", "."))
        unit = m.group(2).casefold()
        if unit not in _UNIT_FAMILY or _UNIT_FAMILY[unit] != target_fam:
            return np.nan
        return amount * _UNIT_FACTORS[unit] / target_factor

    return series.map(one)
'''


def _col(name: str) -> str:
    return f"df[{name!r}]"


# -- per-op code emitters ----------------------------------------------------
def _remove_symbols(params: dict, c: str) -> list[str]:
    chain = "".join(f".replace({s!r}, '')" for s in params.get("symbols", []))
    return [f"    {_col(c)} = _smap({_col(c)}, lambda v: v{chain})"]


def _replace(params: dict, c: str) -> list[str]:
    if params.get("regex", True):
        return [f"    {_col(c)} = _smap({_col(c)}, lambda v: re.sub({params['pattern']!r}, {params.get('repl','')!r}, v))"]
    return [f"    {_col(c)} = _smap({_col(c)}, lambda v: v.replace({params['pattern']!r}, {params.get('repl','')!r}))"]


def _cast(params: dict, c: str) -> list[str]:
    to = str(params["to"]).lower()
    expr = {
        "float": f"pd.to_numeric({_col(c)}, errors='coerce').astype('float64')",
        "int": f"pd.to_numeric({_col(c)}, errors='coerce').round().astype('Int64')",
        "integer": f"pd.to_numeric({_col(c)}, errors='coerce').round().astype('Int64')",
        "string": f"{_col(c)}.astype('string')",
        "str": f"{_col(c)}.astype('string')",
        "datetime": f"pd.to_datetime({_col(c)}, errors='coerce')",
        "category": f"{_col(c)}.astype('category')",
    }.get(to)
    if expr is None:
        return [f"    # NOTE: cast to {to!r} not reproduced", ]
    return [f"    {_col(c)} = {expr}"]


def _normalize_values(params: dict, c: str) -> list[str]:
    mapping = params.get("map", {})
    if params.get("case_insensitive"):
        return [
            f"    _m = {{str(k).strip().casefold(): v for k, v in {mapping!r}.items()}}",
            f"    {_col(c)} = _smap({_col(c)}, lambda v: _m.get(v.strip().casefold(), v))",
        ]
    return [
        f"    _m = {mapping!r}",
        f"    {_col(c)} = {_col(c)}.map(lambda v: _m.get(v, v) if isinstance(v, str) else v)",
    ]


def _parse_date_gen(params: dict, c: str) -> list[str]:
    formats = params.get("formats")
    args = []
    if formats:
        args.append(f"formats={list(formats)!r}")
    if params.get("dayfirst"):
        args.append("dayfirst=True")
    out = params.get("output", "%Y-%m-%d")
    if out != "%Y-%m-%d":
        args.append(f"output={out!r}")
    return [f"    {_col(c)} = _parse_date({_col(c)}{', ' + ', '.join(args) if args else ''})"]


def _parse_number_gen(params: dict, c: str) -> list[str]:
    args = []
    if params.get("decimal", ".") != ".":
        args.append(f"decimal={params['decimal']!r}")
    if params.get("thousands", ",") != ",":
        args.append(f"thousands={params['thousands']!r}")
    if params.get("symbols"):
        args.append(f"symbols={list(params['symbols'])!r}")
    tail = (", " + ", ".join(args)) if args else ""
    return [f"    {_col(c)} = _parse_number({_col(c)}{tail})"]


def _extract_currency_gen(params: dict, c: str) -> list[str]:
    to = params.get("to") or f"{c}_currency"
    default = params.get("default")
    return [f"    df[{to!r}] = {_col(c)}.map(lambda v: _detect_currency(v, {default!r}))"]


def _normalize_unit_gen(params: dict, c: str) -> list[str]:
    to = params.get("to", "g")
    return [f"    {_col(c)} = _normalize_unit({_col(c)}, to={to!r})"]


_SIMPLE: dict[str, str] = {
    "strip_whitespace": "lambda v: v.strip()",
    "collapse_whitespace": "lambda v: re.sub(r'\\s+', ' ', v).strip()",
    "lowercase": "lambda v: v.lower()",
    "uppercase": "lambda v: v.upper()",
    "title_case": "lambda v: re.sub(r'\\s+', ' ', v).strip().title()",
    "capitalize": "lambda v: v.strip().capitalize()",
    "normalize_email": "lambda v: v.strip().lower()",
}

_EMITTERS: dict[str, Callable[[dict, str], list[str]]] = {
    "remove_symbols": _remove_symbols,
    "replace": _replace,
    "cast": _cast,
    "normalize_values": _normalize_values,
    "parse_date": _parse_date_gen,
    "parse_number": _parse_number_gen,
    "extract_currency": _extract_currency_gen,
    "normalize_unit": _normalize_unit_gen,
}


def _emit_column_op(op: Op, source: str) -> list[str]:
    if op.name in _SIMPLE:
        return [f"    {_col(source)} = _smap({_col(source)}, {_SIMPLE[op.name]})"]
    if op.name in _EMITTERS:
        return _EMITTERS[op.name](op.params, source)
    if op.name == "to_na":
        tokens = op.params.get("tokens")
        arg = f", tokens={list(tokens)!r}" if tokens else ""
        return [f"    {_col(source)} = _to_na({_col(source)}{arg})"]
    if op.name == "normalize_phone":
        cc = op.params.get("default_country_code")
        arg = f"default_country_code={cc!r}" if cc else ""
        return [f"    {_col(source)} = _normalize_phone({_col(source)}{', ' + arg if arg else ''})"]
    if op.name == "fill_na":
        if op.params.get("strategy"):
            return [f"    # fill_na strategy={op.params['strategy']!r} — adjust as needed",
                    f"    {_col(source)} = {_col(source)}.fillna({_col(source)}.median() if pd.api.types.is_numeric_dtype({_col(source)}) else '')"]
        return [f"    {_col(source)} = {_col(source)}.fillna({op.params.get('value')!r})"]
    if op.name == "round":
        return [f"    {_col(source)} = pd.to_numeric({_col(source)}, errors='coerce').round({op.params.get('decimals', 0)})"]
    return [f"    # NOTE: op {op.name!r} is not reproduced by codegen"]


def generate_code(recipe: Recipe, func_name: str = "clean") -> str:
    """Render ``recipe`` to a standalone pandas module defining ``func_name(df)``."""
    tokens = "{" + ", ".join(repr(t) for t in sorted(t.casefold() for t in DEFAULT_NA_TOKENS if t)) + "}"
    lines: list[str] = [_HEADER.replace("{tokens}", tokens)]
    lines.append("")
    lines.append(f"def {func_name}(df):")
    lines.append('    """Clean a DataFrame according to the exported recipe. Returns a new frame."""')
    lines.append("    df = df.copy()")

    for col_recipe in recipe.columns:
        if not col_recipe.ops and not col_recipe.rename_to:
            continue
        lines.append("")
        lines.append(f"    # --- {col_recipe.source} ---")
        for op in col_recipe.ops:
            lines.extend(_emit_column_op(op, col_recipe.source))

    renames = {c.source: c.rename_to for c in recipe.columns if c.rename_to}
    if renames:
        lines.append("")
        lines.append(f"    df = df.rename(columns={renames!r})")

    for op in recipe.frame_ops:
        lines.append("")
        if op.name == "dedup":
            subset = op.params.get("subset")
            keep = op.params.get("keep", "first")
            if op.params.get("ignore_case"):
                lines.append("    # NOTE: recipe used case-insensitive dedup; this is the exact-match form")
            lines.append(f"    df = df.drop_duplicates(subset={subset!r}, keep={keep!r})")
        elif op.name == "drop_columns":
            lines.append(f"    df = df.drop(columns={op.params.get('columns', [])!r}, errors='ignore')")

    if recipe.validations:
        lines.append("")
        lines.append("    # Validation rules (enforced by CleanFrame; advisory here):")
        for v in recipe.validations:
            lines.append(f"    #   {v.column}: {v.check}  (on_fail={v.on_fail})")

    lines.append("")
    lines.append("    return df")
    lines.append("")
    return "\n".join(lines)


__all__ = ["generate_code"]
